// Generated by CoffeeScript 1.3.3
(function() {
  var rest;

  rest = require('request');

  exports.cypher = function(url, query, params, cb) {
    return rest({
      method: 'POST',
      json: true,
      url: url,
      body: {
        statements: [
          {
            statement: query,
            parameters: params
          }
        ]
      }
    }, function(error, response, body) {
      var cols, data, i, map, result, row, val, _i, _j, _len, _len1;
      if (!error && response.statusCode === 200 && body) {
        cols = body.results[0].columns;
        data = body.results[0].data;
        result = [];
        for (_i = 0, _len = data.length; _i < _len; _i++) {
          row = data[_i];
          map = {};
          for (i = _j = 0, _len1 = row.length; _j < _len1; i = ++_j) {
            val = row[i];
            map[cols[i]] = val;
          }
          result.push(map);
        }
        cb(null, result);
      } else {
        cb(body, null);
      }
    });
  };

}).call(this);
